### Задание 1

In [49]:
import numpy as np

In [52]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [54]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 2

In [81]:
a_centered = a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [105]:
result = np.dot(a_centered[:,0],a_centered[:,1])
result

8.0

In [106]:
result_fin = result/(len(a_centered[:,0])-1)
result_fin

2.0

### Задание 4

In [107]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

In [108]:
result_fin == np.cov(a.T)[0,1]

True