In [108]:
import numpy as np

In [109]:
# 1
# Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [110]:
# 2
# Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1
b1 = a.reshape(2,6)
b2 = a.reshape(3,4)
b3 = a.reshape(4,3)
b4 = a.reshape(6,2)
b5 = a.reshape(12,1)
b1,b2,b3,b4,b5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

In [111]:
# 3
# Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 
# (в трех примерах - для обозначения числа столбцов, в двух - для строк)
c1 = a.reshape(-1,6)
c2 = a.reshape(-1,4)
c3 = a.reshape(-1,3)
c4 = a.reshape(6,-1)
c5 = a.reshape(12,-1)
c1,c2,c3,c4,c5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

In [112]:
# 4
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
# - Нет, т.к. чтобы описать его элемент, нужно два индекса

In [113]:
# 5
# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
# со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же
# атрибутом size, как и исходный массив.

d = np.random.randn(3, 4)
print(d.size)
d = d.flatten()
print(d.size)
d

12
12


array([-0.88385744,  0.15372511,  0.05820872, -1.1429703 ,  0.35778736,
        0.56078453,  1.08305124,  1.05380205, -1.37766937, -0.93782504,
        0.51503527,  0.51378595])

In [114]:
# 6
# Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [115]:
# 7
# Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 
# невключительно с интервалом 2. В чем разница между массивами a и b?
b = np.arange(20, 0, -2).reshape(1,10)
b

# Разница в том, что прошлый массив одномерный, этот - двумерный

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [116]:
# 8
# Вертикально соединить массивы a и b. a - двумерный массив из нулей, число 
# строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b,
# состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
a = np.zeros((2,2))
b = np.ones((3,2))
c = np.concatenate((a,b),axis=0)
print(c.size)
c

10


array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [117]:
# 9
# Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), 
# состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
# Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
# Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
a = np.arange(12)
A = a.reshape(4,3)
print(A)
At = np.transpose(A)
print("\n",At)
B = np.matmul(A,At)
print("\n",B)
print("\n",B.size)
# from numpy import linalg
# linalg.inv(B)
# Обратную матрицу получить не выйдет, т.к. матрица B - вырожденная (ее определитель равен 0)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

 16


In [118]:
# 10
# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
from numpy import random
random.seed(42)

In [119]:
# 11
# Создайте одномерный массив c, составленный из последовательности 16-ти 
# случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
c = random.randint(1,16,16)
c

array([ 7,  4, 13, 15, 11,  8, 13,  5,  7, 10,  3,  7, 11, 11,  8,  5])

In [120]:
C = c.reshape(4,4)
C

array([[ 7,  4, 13, 15],
       [11,  8, 13,  5],
       [ 7, 10,  3,  7],
       [11, 11,  8,  5]])

In [121]:
D = B + (C*10)
D

array([[ 75,  54, 153, 182],
       [124, 130, 216, 172],
       [ 93, 186, 179, 282],
       [142, 232, 292, 352]])

In [122]:
print(linalg.det(D))
print(linalg.matrix_rank(D))
D_inv = linalg.inv(D)
print(D_inv)

-34571999.99999998
4
[[ 9.40645609e-03  3.68853407e-02  4.95776929e-02 -6.26055768e-02]
 [-1.50468587e-02  4.55860234e-04  5.43792665e-05  7.51359482e-03]
 [-3.59250260e-03 -1.39396043e-02 -3.69420340e-02  3.82644915e-02]
 [ 9.10274210e-03 -3.61679972e-03  1.06091635e-02 -8.59770913e-03]]


In [123]:
D_inv=np.where(D_inv<0, 0,1)
D_inv

array([[1, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [124]:
print(B)
print(C)
E=np.where(D_inv==1, B, C)
E

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 7  4 13 15]
 [11  8 13  5]
 [ 7 10  3  7]
 [11 11  8  5]]


array([[  5,  14,  23,  15],
       [ 11,  50,  86, 122],
       [  7,  10,   3, 212],
       [ 32,  11, 212,   5]])